version: "3.9"
services:
  
  api:
    container_name: languagesloth_api
    build: ./LanguageSloth_API
    ports:
      - "8080:8080"

  frontend:
    container_name: languagesloth_frontend
    build: ./LanguageSloth_Frontend
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"

  tts:
    container_name: languagesloth_tts
    build: ./TTS
    ports:
      - "5001:5001"
    volumes:
      - languagesloth_tts:/root/.local/share/tts/

  lingva:
    container_name: languagesloth_lingva
    image: thedaviddelta/lingva-translate:latest
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  languagesloth_tts: